name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch

categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "maintenance"
      - "refactor"
      - "cleanup"
  - title: "📖 Documentation"
    labels:
      - "documentation"
      - "docs"
  - title: "🧩 Dependency Updates"
    labels:
      - "deps"
      - "dependencies"
      - "bump"
      - "chore"
    collapse-after: 5
    collapse-label: "View more dependency updates"
  - title: "🔬 Others"
    labels:
      - "style"
      - "refactor"
      - "test"
      - "ci"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
