[project]
name = "cookiecutter-python-uv"
version = "0.5.0"
description = "A python cookiecutter application to create a new python project that uses uv to manage its dependencies."
authors = [{ name = "Wyatt Ferguson", email = "wyattxdev@duck.com" }]
license = { text = "MIT" }
readme = "README.md"
keywords = ['cookiecutter', 'template', 'uv', 'python', 'project', 'generator']
requires-python = ">=3.12"
dependencies = [
  "cookiecutter>=2.1.1"
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: >=3.12",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Code Generators",
]

[project.urls]
Repository = "https://github.com/wyattferguson/cookiecutter-project"
Documentation = "https://github.com/wyattferguson/cookiecutter-project"
Homepage = "https://github.com/wyattferguson/cookiecutter-project"
