site_name: {{cookiecutter.repository_name}}
repo_url: https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.repository_name}}
site_url: https://{{cookiecutter.github_username}}.github.io/{{cookiecutter.repository_name}}
site_description: {{cookiecutter.project_description}}
site_author: {{cookiecutter.author}}
edit_uri: edit/main/docs/
repo_name: {{cookiecutter.github_username}}/{{cookiecutter.repository_name}}
copyright: Maintained by <a href="https://github.com/{{cookiecutter.github_username}}">{{cookiecutter.author}}</a>.

nav:
  - Home: index.md
  - Modules: reference/
  - License: license.md
plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          paths: ["{{cookiecutter.project_name}}"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.repository_name}}

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
